export const GET_ALL_PROJECT = 'GET_ALL_PROJECT'
export const SET_SUBMIT_EDIT_PROJECT = 'SET_SUBMIT_EDIT_PROJECT'
export const SET_PROJECT_DETAIL = 'SET_PROJECT_DETAIL'
export const PUT_PROJECT_DETAIL = 'PUT_PROJECT_DETAIL'