export const SIGN_IN_ACTION = 'SIGN_IN_ACTION'
export const GET_USER_SEARCH = 'GET_USER_SEARCH'
export const SET_USER_BY_PROJECTID = 'SET_USER_BY_PROJECTID'
export const REMOVE_USER_ASSIGNESS = 'REMOVE_USER_ASSIGNESS'